// scripts/rpd/lib/gallery.js — self-contained index.html from a run's
// manifest.json. Relative video paths so the folder deploys to Cloudflare
// Pages as-is; CSS/JS are inline (no CDN). The seed URL is the one allowed
// remote asset: judging the original product image is the point of the
// page, and it must appear LARGE plus a CSS-brightened twin (dark products
// disappear on a dark page — owner standing rule).
//
// Rebuild anytime, including mid-run: missing cells / videos / costs
// render as placeholders, never throw. Missing manifest throws — there
// is nothing to show.
//
//   const { buildGallery } = require('./lib/gallery');
//   buildGallery(runDir) → `${runDir}/index.html`

'use strict';

const fs = require('fs');
const path = require('path');
const { readManifest } = require('./manifest');

const STATUSES = ['done', 'failed', 'skipped', 'submitted', 'processing', 'planned', 'submitting'];
const LEVERS = ['baseline', 'guidance', 'raw', 'directives', 'patch'];

function buildGallery(runDir) {
  if (!runDir) throw new Error('rpd gallery: runDir required');
  const root = path.resolve(String(runDir));
  const manifest = readManifest(root);
  if (!manifest || typeof manifest !== 'object' || Array.isArray(manifest)) {
    throw new Error('rpd gallery: manifest.json must be an object');
  }
  const outPath = path.join(root, 'index.html');
  fs.writeFileSync(outPath, renderHtml(manifest, root), 'utf8');
  return outPath;
}

// ── render ──────────────────────────────────────────────────────────────────

function renderHtml(m, runDir) {
  const spec = isObj(m.spec) ? m.spec : {};
  const seed = isObj(spec.seed) ? spec.seed : {};
  const cells = Array.isArray(m.cells) ? m.cells.filter(isObj) : [];
  const observations = Array.isArray(m.observations) ? m.observations.filter(isObj) : [];
  const variants = unionVariants(spec, cells);
  const models = unionModels(spec, cells);
  const byKey = indexCells(cells);

  const name = str(m.name) || 'untitled run';
  const createdAt = formatWhen(m.createdAt);
  const aspect = str(spec.aspectRatio) || '—';
  const duration = formatDuration(spec.durationSec);
  const resolution = str(spec.resolution) || '—';
  const totals = tally(cells);
  const runNotes = str(m.notes);

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(name)} — RPD</title>
${css(safeHex(seed.brandHex))}
</head>
<body>
<!-- generated by scripts/rpd/lib/gallery.js — rebuild, do not edit -->
<header class="hdr">
  <div class="hdr-top">
    <h1>${esc(name)}</h1>
    <p class="hdr-meta">
      <span>${esc(createdAt || 'undated')}</span>
      <span>${esc(aspect)}</span>
      <span>${esc(duration)}</span>
      <span>${esc(resolution)}</span>
    </p>
  </div>
  ${runNotes ? `<p class="hdr-notes">${esc(runNotes)}</p>` : ''}
  <div class="totals" aria-label="run totals">
    <span class="chip chip-settled">settled $${esc(totals.settled)}</span>
    <span class="chip chip-est">est remainder $~${esc(totals.estRemainder)}</span>
    ${STATUSES.map((s) =>
      totals.byStatus[s]
        ? `<span class="chip chip-st chip-st-${s}">${totals.byStatus[s]} ${s}</span>`
        : ''
    ).join('')}
    ${totals.other ? `<span class="chip chip-st">${totals.other} other</span>` : ''}
    <span class="chip">${cells.length} cells</span>
  </div>
  ${renderRunObs(observations)}
</header>
${renderSeed(seed)}
${renderMatrix({ variants, models, byKey, spec, observations, runDir })}
${zoomOverlay()}
${zoomScript()}
</body>
</html>
`;
}

function renderSeed(seed) {
  // http(s) only: a javascript:/data: seed URL must never become a
  // clickable href/src (spec is operator-controlled, but specs get shared).
  const url = /^https?:\/\//i.test(str(seed.url)) ? str(seed.url) : '';
  const title = str(seed.productTitle);
  const refs = normalizeRefs(seed.refs).filter((r) => /^https?:\/\//i.test(r));
  const hex = safeHex(seed.brandHex);

  const original = url
    ? `<figure class="seed-fig">
        <a class="seed-link" href="${escAttr(url)}" target="_blank" rel="noopener noreferrer" title="open full size">
          <img class="seed-img seed-original" src="${escAttr(url)}" alt="${escAttr(title || 'seed')}" data-full="${escAttr(url)}">
        </a>
        <figcaption>original${title ? ` — ${esc(title)}` : ''}</figcaption>
      </figure>`
    : `<figure class="seed-fig seed-missing"><figcaption>no seed url</figcaption></figure>`;

  const bright = url
    ? `<figure class="seed-fig">
        <img class="seed-img seed-bright" src="${escAttr(url)}" alt="${escAttr((title || 'seed') + ' (brightened)')}" data-full="${escAttr(url)}">
        <figcaption>brightened for dark products</figcaption>
      </figure>`
    : '';

  const refThumbs = refs.length
    ? `<div class="seed-refs" aria-label="seed refs">
        ${refs.map((r, i) =>
          `<a href="${escAttr(r)}" target="_blank" rel="noopener noreferrer">
             <img class="seed-ref" src="${escAttr(r)}" alt="ref ${i + 1}" data-full="${escAttr(r)}">
           </a>`
        ).join('')}
      </div>`
    : '';

  const swatch = hex
    ? `<span class="swatch" style="background:${escAttr(hex)}" title="${escAttr(hex)}"></span><span class="swatch-hex">${esc(hex)}</span>`
    : '';

  return `<section class="seed" aria-label="seed">
  <h2>Seed ${swatch}</h2>
  <div class="seed-pair">
    ${original}
    ${bright}
  </div>
  ${refThumbs}
</section>`;
}

function renderRunObs(observations) {
  const run = observations.filter((o) => !o.scope || o.scope === 'run');
  if (!run.length) return '';
  return `<section class="obs-run" aria-label="observations">
    <h2>Observations</h2>
    <ul>
      ${run.map((o) =>
        `<li><time>${esc(formatWhen(o.at) || '')}</time> ${esc(str(o.text))}</li>`
      ).join('')}
    </ul>
  </section>`;
}

function renderMatrix({ variants, models, byKey, spec, observations, runDir }) {
  if (!variants.length && !models.length) {
    return `<p class="empty-matrix">no variants or models yet</p>`;
  }
  const head = `<tr>
    <th class="corner">variant \\ model</th>
    ${models.map((model) =>
      `<th class="col-label" title="${escAttr(model)}">${esc(shortModel(model))}</th>`
    ).join('')}
  </tr>`;

  const rows = variants.map((variant) => {
    const vid = str(variant.id) || '(none)';
    const tds = models.map((model) => {
      const cell = byKey.get(cellKey(model, vid));
      return `<td class="cell-td">${renderCell(cell, { variant, model, spec, observations, runDir })}</td>`;
    }).join('');
    return `<tr>
      <th class="row-label" title="${escAttr(vid)}">${esc(vid)}</th>
      ${tds}
    </tr>`;
  }).join('');

  return `<div class="matrix-wrap">
  <table class="matrix">
    <thead>${head}</thead>
    <tbody>${rows}</tbody>
  </table>
</div>`;
}

function renderCell(cell, ctx) {
  if (!cell) {
    return `<article class="cell cell-missing"><p class="cell-empty">not minted</p></article>`;
  }
  const status = str(cell.status) || 'unknown';
  const failed = status === 'failed' || status === 'skipped';
  const lever = normalizeLever(cell.promptMeta && cell.promptMeta.lever);
  const duration = formatDuration(
    firstFinite(cell.durationSec, ctx.variant && ctx.variant.durationSec, ctx.spec.durationSec)
  );
  const resolution = str(cell.resolution)
    || str(ctx.variant && ctx.variant.resolution)
    || str(ctx.spec.resolution)
    || '—';
  const videoSrc = pickVideoSrc(cell, ctx.runDir);
  const pred = str(cell.predictionId);
  const latency = formatLatency(cell.latencyMs);

  const chips = [
    chip(shortModel(cell.model || ctx.model), 'chip-model', cell.model || ctx.model),
    chip(duration, 'chip-dur'),
    chip(resolution, 'chip-res'),
    costChip(cell),
    latency ? chip(latency, 'chip-lat') : '',
    pred ? `<span class="chip chip-pred" title="${escAttr(pred)}">${esc(pred)}</span>` : '',
    lever ? `<span class="chip chip-lever lever-${escAttr(lever)}">${esc(lever)}</span>` : '',
    `<span class="chip chip-st chip-st-${escAttr(status)}">${esc(status)}</span>`,
    chargedChip(cell)
  ].filter(Boolean).join('');

  let body;
  if (failed) {
    body = `<div class="cell-error" role="alert">${esc(str(cell.error) || status)}</div>`;
  } else if (videoSrc) {
    body = `<video class="cell-video" controls loop muted playsinline preload="metadata" src="${escAttr(videoSrc)}"></video>`;
  } else if (status === 'submitted' || status === 'processing' || status === 'submitting') {
    body = `<div class="cell-pending">in flight${pred ? ` · ${esc(pred)}` : ''}</div>`;
  } else if (status === 'planned') {
    body = `<div class="cell-pending">not submitted</div>`;
  } else {
    body = `<div class="cell-pending">no local video yet</div>`;
  }

  return `<article class="cell cell-${escAttr(status)}" data-cell="${escAttr(str(cell.id))}">
    <div class="chips">${chips}</div>
    ${body}
    ${renderCellNotes(cell, ctx.observations)}
    ${renderTimings(cell)}
    ${renderPrompt(cell)}
  </article>`;
}

// Timing telemetry for forecasting how a change moves total wall-clock:
// harness-measured phases + Atlas's own executionTime/timings + the
// Cloudinary transform probes (cold derivation is real production latency).
function renderTimings(cell) {
  const t = isObj(cell.timings) ? cell.timings : null;
  if (!t) return '';
  const rows = [];
  const row = (label, value) => {
    if (value == null || value === '') return;
    rows.push(`<tr><td>${esc(label)}</td><td>${esc(value)}</td></tr>`);
  };
  const ms = (n) => (Number.isFinite(Number(n)) ? `${(Number(n) / 1000).toFixed(1)}s` : null);
  row('prompt build', Number.isFinite(Number(t.promptBuildMs)) ? `${t.promptBuildMs}ms` : null);
  row('submit round-trip', ms(t.submitMs));
  row('queue → terminal', ms(t.queueToTerminalMs));
  if (t.atlasExecutionTime != null) row('atlas executionTime', String(t.atlasExecutionTime));
  if (isObj(t.atlasTimings)) {
    for (const [k, v] of Object.entries(t.atlasTimings)) row(`atlas ${k}`, String(v));
  }
  row('download', ms(t.downloadMs));
  if (Number.isFinite(Number(t.downloadBytes))) row('video size', `${(t.downloadBytes / 1048576).toFixed(1)} MB`);
  row('titling', ms(t.titlingMs));
  if (isObj(t.titling)) {
    for (const [k, v] of Object.entries(t.titling)) row(`titling ${k}`, String(v));
  }
  const probes = Array.isArray(t.seedProbe) ? t.seedProbe.filter(isObj) : [];
  const probeRows = probes.map((p, i) => {
    const bits = [
      Number.isFinite(Number(p.ms)) ? `${p.ms}ms` : '?',
      Number.isFinite(Number(p.bytes)) ? `${Math.round(p.bytes / 1024)}KB` : null,
      p.cache ? `cache:${p.cache}` : null,
      p.status && p.status >= 400 ? `HTTP ${p.status}` : null,
      p.error ? `error: ${p.error}` : null
    ].filter(Boolean).join(' · ');
    return `<tr><td>ref ${i} transform</td><td title="${escAttr(str(p.url))}">${esc(bits)}</td></tr>`;
  });
  if (!rows.length && !probeRows.length) return '';
  return `<details class="timings">
    <summary>timings</summary>
    <table class="timings-table"><tbody>${rows.join('')}${probeRows.join('')}</tbody></table>
  </details>`;
}

function renderCellNotes(cell, observations) {
  const own = Array.isArray(cell.notes) ? cell.notes.filter(isObj) : [];
  const scoped = (Array.isArray(observations) ? observations : [])
    .filter((o) => o.scope && o.scope === cell.id);
  const all = own.concat(scoped);
  if (!all.length) return '';
  return `<ul class="cell-notes">
    ${all.map((n) =>
      `<li><time>${esc(formatWhen(n.at) || '')}</time> ${esc(str(n.text))}</li>`
    ).join('')}
  </ul>`;
}

function renderPrompt(cell) {
  const prompt = str(cell.prompt);
  const meta = isObj(cell.promptMeta) ? cell.promptMeta : {};
  const diff = Array.isArray(meta.baselineDiff) ? meta.baselineDiff : null;
  if (!prompt && !(diff && diff.length)) return '';
  const inner = diff && diff.length
    ? renderDiff(diff)
    : `<pre class="prompt-text">${esc(prompt)}</pre>`;
  return `<details class="prompt">
    <summary>prompt</summary>
    ${inner}
  </details>`;
}

function renderDiff(diff) {
  const lines = diff.map((part) => {
    const p = isObj(part) ? part : { type: 'same', text: String(part == null ? '' : part) };
    const type = p.type === 'add' || p.type === 'del' ? p.type : 'same';
    const mark = type === 'add' ? '+' : type === 'del' ? '-' : ' ';
    const text = p.text == null ? '' : String(p.text);
    return `<div class="diff-${type}">${esc(mark + text)}</div>`;
  });
  return `<div class="prompt-diff">${lines.join('')}</div>`;
}

function costChip(cell) {
  if (cell.costSource === 'actual') {
    const n = fmtUsd(cell.costUsd);
    return n ? `<span class="chip chip-cost chip-cost-settled">$${esc(n)} settled</span>` : '';
  }
  const n = fmtUsd(
    cell.costSource === 'estimated' ? firstFinite(cell.costUsd, cell.estUsd) : firstFinite(cell.estUsd, cell.costUsd)
  );
  return n ? `<span class="chip chip-cost chip-cost-est">$~${esc(n)} est (floor)</span>` : '';
}

function chargedChip(cell) {
  if (cell.charged === true) return `<span class="chip chip-charged">charged</span>`;
  if (cell.charged === false) return `<span class="chip chip-uncharged">uncharged</span>`;
  return '';
}

function chip(text, cls, title) {
  if (!text) return '';
  const t = title ? ` title="${escAttr(title)}"` : '';
  return `<span class="chip ${cls || ''}"${t}>${esc(text)}</span>`;
}

function zoomOverlay() {
  return `<div id="seed-zoom" hidden>
  <button type="button" class="seed-zoom-close" aria-label="close">×</button>
  <img alt="">
</div>`;
}

function zoomScript() {
  // Tiny click-to-zoom. URLs stay on data-full / src — never concatenated
  // into a JS string from the manifest.
  return `<script>
(function () {
  var ov = document.getElementById('seed-zoom');
  if (!ov) return;
  var img = ov.querySelector('img');
  document.addEventListener('click', function (e) {
    var t = e.target;
    if (!t) return;
    if (t.classList && (t.classList.contains('seed-img') || t.classList.contains('seed-ref'))) {
      e.preventDefault();
      img.src = t.getAttribute('data-full') || t.src;
      ov.hidden = false;
      return;
    }
    if (t.id === 'seed-zoom' || (t.classList && t.classList.contains('seed-zoom-close'))) {
      ov.hidden = true;
      img.removeAttribute('src');
    }
  });
  document.addEventListener('keydown', function (e) {
    if (e.key === 'Escape') { ov.hidden = true; img.removeAttribute('src'); }
  });
})();
</script>`;
}

function css(accentHex) {
  const accent = accentHex || '#6ee7b7';
  return `<style>
:root {
  --bg: #0e1014;
  --surface: #171a21;
  --surface-2: #1e232d;
  --ink: #e8eaef;
  --muted: #8b93a7;
  --line: #2a3040;
  --accent: ${accent};
  --fail: #f87171;
  --ok: #34d399;
  --warn: #fbbf24;
  --add: #34d399;
  --del: #f87171;
}
* { box-sizing: border-box; }
html, body { margin: 0; padding: 0; background: var(--bg); color: var(--ink);
  font: 14px/1.45 -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif; }
.hdr { padding: 24px 24px 8px; border-bottom: 1px solid var(--line); }
.hdr-top { display: flex; flex-wrap: wrap; gap: 8px 24px; align-items: baseline; }
h1 { font-size: 1.45rem; font-weight: 650; margin: 0; letter-spacing: -0.02em; }
h2 { font-size: 0.85rem; text-transform: uppercase; letter-spacing: 0.06em; color: var(--muted);
  margin: 0 0 12px; font-weight: 600; }
.hdr-meta { display: flex; flex-wrap: wrap; gap: 10px; color: var(--muted); margin: 0; }
.hdr-meta span::before { content: "·"; margin-right: 10px; color: var(--line); }
.hdr-meta span:first-child::before { content: none; margin: 0; }
.hdr-notes { color: var(--muted); max-width: 72ch; }
.totals { display: flex; flex-wrap: wrap; gap: 6px; margin: 14px 0; }
.chip { display: inline-block; padding: 2px 8px; border-radius: 999px; background: var(--surface-2);
  border: 1px solid var(--line); color: var(--ink); font-size: 12px; line-height: 1.6; }
.chip-settled, .chip-cost-settled { border-color: #14532d; background: #052e16; color: var(--ok); }
.chip-est, .chip-cost-est { color: var(--warn); }
.chip-pred { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  font-size: 10px; color: var(--muted); max-width: 14em; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.chip-st-done { color: var(--ok); }
.chip-st-failed { color: var(--fail); }
.chip-st-skipped { color: var(--muted); }
.chip-st-submitted, .chip-st-processing, .chip-st-submitting { color: #93c5fd; }
.chip-st-planned { color: var(--muted); }
.chip-lever { text-transform: lowercase; }
.lever-raw { border-color: #9a3412; color: #fdba74; }
.lever-guidance { color: #93c5fd; }
.lever-directives { color: #c4b5fd; }
.lever-patch { color: var(--warn); }
.lever-baseline { color: var(--muted); }
.chip-charged { color: var(--fail); }
.chip-uncharged { color: var(--muted); }
.obs-run { margin: 16px 0 8px; }
.obs-run ul, .cell-notes { margin: 0; padding-left: 1.2em; }
.obs-run li, .cell-notes li { margin: 4px 0; }
.obs-run time, .cell-notes time { color: var(--muted); font-size: 12px; margin-right: 6px; }
.seed { padding: 24px; border-bottom: 1px solid var(--line); }
.seed-pair { display: flex; flex-wrap: wrap; gap: 20px; align-items: flex-start; }
.seed-fig { margin: 0; }
.seed-img { display: block; max-width: 480px; width: 100%; height: auto; background: #000;
  border: 1px solid var(--line); cursor: zoom-in; }
.seed-bright { filter: brightness(1.6) saturate(1.1); }
.seed-fig figcaption { margin-top: 6px; color: var(--muted); font-size: 12px; }
.seed-missing { width: 240px; height: 160px; background: var(--surface); border: 1px dashed var(--line);
  display: flex; align-items: center; justify-content: center; }
.seed-refs { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 14px; }
.seed-ref { width: 88px; height: 88px; object-fit: cover; border: 1px solid var(--line); cursor: zoom-in; background: #000; }
.swatch { display: inline-block; width: 12px; height: 12px; border-radius: 2px; border: 1px solid var(--line);
  vertical-align: middle; margin: 0 6px; }
.swatch-hex { color: var(--muted); font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 12px; font-weight: 400; text-transform: none; letter-spacing: 0; }
.matrix-wrap { overflow: auto; padding: 16px 16px 48px; }
table.matrix { border-collapse: separate; border-spacing: 10px; min-width: 100%; }
table.matrix thead th { position: sticky; top: 0; z-index: 2; background: var(--bg);
  padding: 10px 12px; text-align: left; font-size: 12px; color: var(--muted); font-weight: 600; }
table.matrix .corner { z-index: 3; left: 0; }
table.matrix .row-label { position: sticky; left: 0; z-index: 1; background: var(--bg);
  text-align: left; vertical-align: top; padding: 12px 10px 12px 0; min-width: 8.5rem; max-width: 14rem;
  font-size: 13px; color: var(--ink); }
table.matrix td.cell-td { vertical-align: top; min-width: 280px; max-width: 420px;
  background: var(--surface); border: 1px solid var(--line); border-radius: 8px; padding: 0; }
.cell { padding: 10px; }
.chips { display: flex; flex-wrap: wrap; gap: 4px; margin-bottom: 8px; }
.cell-video { display: block; width: 100%; max-height: 520px; background: #000; }
.cell-error { background: #3f1212; color: #fecaca; border: 1px solid #7f1d1d; padding: 12px;
  border-radius: 6px; white-space: pre-wrap; word-break: break-word; font-size: 13px; }
.cell-pending, .cell-empty { color: var(--muted); padding: 24px 8px; text-align: center; }
.cell-notes { margin: 8px 0 0; color: var(--ink); font-size: 12px; }
.prompt { margin-top: 8px; border-top: 1px solid var(--line); padding-top: 6px; }
.prompt summary { cursor: pointer; color: var(--muted); font-size: 12px; }
.timings { margin-top: 8px; border-top: 1px solid var(--line); padding-top: 6px; }
.timings summary { cursor: pointer; color: var(--muted); font-size: 12px; }
.timings-table { margin-top: 6px; width: 100%; border-collapse: collapse; font-size: 11px; }
.timings-table td { padding: 2px 6px; border-bottom: 1px solid var(--line); color: var(--muted); }
.timings-table td:first-child { color: var(--ink); white-space: nowrap; }
.prompt-text, .prompt-diff { margin: 8px 0 0; max-height: 18rem; overflow: auto; padding: 8px;
  background: #0b0d11; border: 1px solid var(--line); border-radius: 4px;
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 11px;
  white-space: pre-wrap; word-break: break-word; line-height: 1.4; }
.diff-add { color: var(--add); background: rgba(52, 211, 153, 0.08); }
.diff-del { color: var(--del); background: rgba(248, 113, 113, 0.08); }
.diff-same { color: var(--muted); }
.empty-matrix { padding: 24px; color: var(--muted); }
#seed-zoom { position: fixed; inset: 0; background: rgba(0,0,0,0.88); z-index: 50;
  display: flex; align-items: center; justify-content: center; padding: 24px; }
#seed-zoom[hidden] { display: none !important; }
#seed-zoom img { max-width: 96vw; max-height: 94vh; box-shadow: 0 0 0 1px var(--line); }
.seed-zoom-close { position: absolute; top: 12px; right: 16px; background: transparent; color: var(--ink);
  border: 0; font-size: 28px; cursor: pointer; }
@media (max-width: 640px) {
  .seed-img { max-width: 100%; }
}
</style>`;
}

// ── data helpers ────────────────────────────────────────────────────────────

function unionModels(spec, cells) {
  const listed = Array.isArray(spec.models) ? spec.models.filter(Boolean).map(String) : [];
  const seen = new Set(listed);
  for (const c of cells) {
    if (c.model && !seen.has(c.model)) {
      listed.push(String(c.model));
      seen.add(c.model);
    }
  }
  return listed;
}

function unionVariants(spec, cells) {
  const listed = Array.isArray(spec.variants)
    ? spec.variants.filter(isObj).map((v) => ({ ...v, id: str(v.id) || '(none)' }))
    : [];
  const seen = new Set(listed.map((v) => v.id));
  for (const c of cells) {
    const id = str(c.variantId) || '(none)';
    if (!seen.has(id)) {
      listed.push({ id });
      seen.add(id);
    }
  }
  return listed;
}

function indexCells(cells) {
  const map = new Map();
  for (const c of cells) {
    const key = cellKey(c.model, str(c.variantId) || '(none)');
    if (!map.has(key)) map.set(key, c);
  }
  return map;
}

function cellKey(model, variantId) {
  return `${model || ''}\0${variantId || ''}`;
}

function tally(cells) {
  const byStatus = Object.fromEntries(STATUSES.map((s) => [s, 0]));
  let other = 0;
  let settled = 0;
  let estRemainder = 0;
  for (const c of cells) {
    const st = str(c.status);
    if (STATUSES.includes(st)) byStatus[st] += 1;
    else other += 1;
    if (c.costSource === 'actual' && Number.isFinite(Number(c.costUsd))) {
      settled += Number(c.costUsd);
    } else {
      const rem = firstFinite(c.estUsd, c.costUsd);
      if (Number.isFinite(rem)) estRemainder += rem;
    }
  }
  return {
    settled: fmtUsd(settled) || '0.00',
    estRemainder: fmtUsd(estRemainder) || '0.00',
    byStatus,
    other
  };
}

function pickVideoSrc(cell, runDir) {
  const raw = firstStr(cell.titledPath, cell.localPath);
  if (!raw) return '';
  return toRelative(raw, runDir);
}

function toRelative(p, runDir) {
  const s = String(p).trim();
  if (!s) return '';
  // Remote URLs would play locally but are not Pages-deployable and expire.
  // A mid-run rebuild with only videoUrl set must not silently ship a
  // gallery that dies after the prediction is gone.
  if (/^[a-zA-Z][a-zA-Z0-9+.-]*:/.test(s)) return '';
  if (path.isAbsolute(s) && runDir) {
    const rel = path.relative(runDir, s);
    if (rel && !rel.startsWith('..') && !path.isAbsolute(rel)) {
      return rel.split(path.sep).join('/');
    }
    return '';
  }
  return s.replace(/\\/g, '/').replace(/^\.\//, '');
}

function normalizeRefs(refs) {
  if (!Array.isArray(refs)) return [];
  const out = [];
  for (const r of refs) {
    if (typeof r === 'string' && r.trim()) out.push(r.trim());
    else if (isObj(r) && str(r.url)) out.push(str(r.url));
  }
  return out;
}

function normalizeLever(lever) {
  const s = str(lever).toLowerCase();
  return LEVERS.includes(s) ? s : s || '';
}

function shortModel(model) {
  const s = String(model || '');
  const i = s.lastIndexOf('/');
  return i >= 0 ? s.slice(i + 1) : s;
}

function formatDuration(sec) {
  const n = Number(sec);
  if (!Number.isFinite(n)) return '—';
  return `${n}s`;
}

function formatLatency(ms) {
  const n = Number(ms);
  if (!Number.isFinite(n)) return '';
  return `${(n / 1000).toFixed(1)}s`;
}

function formatWhen(v) {
  if (v == null || v === '') return '';
  if (v instanceof Date && !Number.isNaN(v.getTime())) return v.toISOString();
  return String(v);
}

function fmtUsd(n) {
  const x = Number(n);
  if (!Number.isFinite(x)) return null;
  return x.toFixed(2);
}

function firstFinite(...vals) {
  for (const v of vals) {
    const n = Number(v);
    if (Number.isFinite(n)) return n;
  }
  return undefined;
}

function firstStr(...vals) {
  for (const v of vals) {
    if (v != null && String(v).trim()) return String(v).trim();
  }
  return '';
}

function safeHex(h) {
  if (typeof h !== 'string') return '';
  const s = h.trim();
  return /^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$/.test(s) ? s : '';
}

function isObj(v) {
  return !!v && typeof v === 'object' && !Array.isArray(v);
}

function str(v) {
  if (v == null) return '';
  return String(v);
}

// Escape every manifest-derived string. Used for both text and quoted
// attributes — attribute context still needs quotes in the template.
function esc(v) {
  return String(v == null ? '' : v)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

const escAttr = esc;

module.exports = { buildGallery };
