// Overlay placement — 4-box anchored algorithm for image-as-canvas
// templates (testimonial_overlay, product_overlay).
//
// Two corners are anchored at fixed rects and two zones (headline +
// the lower-half element, either product_meta or quote) are placed
// where they LEAST violate the subject + density grid in their
// respective half. No priority cascade, no shape variants, no inset
// fallback — every overlay always renders the same 4 boxes (filtered
// by the template's element_priority_order ids).
//
// Inputs the placement reads:
//   - canvasW / canvasH (px units of the canvas; rect output is in % of canvas)
//   - analysis: { primarySubjectRectPct, densityGrid, ... } from
//     OverlayZoneArtifact. May be null when analysis hasn't run; the
//     placement still emits the 4 boxes at their nominal positions.
//   - elementIds: the per-template filter (logo, headline, cta,
//     plus quote OR product_meta).
//
// Output shape matches what the renderer expects (rectPct,
// variant, fontScale, scrim, textColor) so existing
// renderPlacedElement / renderOverlay* code keeps working.

// ── Box geometry tunables ────────────────────────────────────────────
// All values are FRACTIONS of canvas (0..1).
const LOGO_RECT      = { x1: 0.04, y1: 0.04, x2: 0.20, y2: 0.10 };
const CTA_RECT       = { x1: 0.68, y1: 0.86, x2: 0.96, y2: 0.94 };

const HEADLINE_BOX = {
  yMin: 0.10, yMax: 0.50,   // upper half (search range, top + bottom edges)
  xMin: 0.04, xMax: 0.96,
  minW: 0.50, minH: 0.12,
  maxW: 0.92, maxH: 0.30
};

const LOWER_BOX = {
  yMin: 0.50, yMax: 0.86,   // lower half (above the cta corner band)
  xMin: 0.04, xMax: 0.96,
  minW: 0.50, minH: 0.16,
  maxW: 0.92, maxH: 0.34
};

// Search density for least-violating placement. SCAN_STEPS controls the
// number of candidate positions considered along each axis.
const SCAN_STEPS = 12;

// Scoring weights — subject overlap dominates; density is a soft
// preference for less-busy regions.
const SUBJECT_OVERLAP_WEIGHT = 100;
const DENSITY_WEIGHT         = 30;

// ── Entry point ──────────────────────────────────────────────────────

function placeOverlays({ canvasW = 1000, canvasH = 1000, analysis, content, brandColors, aspectRatio, elementIds }) {
  const allowed = new Set(Array.isArray(elementIds) ? elementIds : []);
  const elements   = [];
  const decisions  = [];
  const skipped    = [];

  // Anchored: logo (top-left)
  if (allowed.has('logo')) {
    if (content?.brand?.logo) {
      elements.push(makeOverlayElement('logo', LOGO_RECT));
      decisions.push({ id: 'logo', state: 'placed', mode: 'anchored-tl', rectPct: LOGO_RECT });
    } else {
      skipped.push({ id: 'logo', reason: 'no brand.logo source', _missingPath: 'brand.logo' });
    }
  }

  // Anchored: cta (bottom-right). Always place when the template
  // wants it — text is generated by the derivation LLM AFTER
  // placement, so gating on content?.cta?.text would skip the box
  // before Gemini has a chance to fill it.
  if (allowed.has('cta')) {
    elements.push(makeOverlayElement('cta', CTA_RECT));
    decisions.push({ id: 'cta', state: 'placed', mode: 'anchored-br', rectPct: CTA_RECT });
  }

  // Floating: headline (upper half, least-violating)
  if (allowed.has('headline')) {
    const rect = findLeastViolatingRect(analysis, HEADLINE_BOX);
    elements.push(makeOverlayElement('headline', rect));
    decisions.push({ id: 'headline', state: 'placed', mode: 'least-violating-upper', rectPct: rect });
  }

  // Floating: lower-half slot. testimonial_overlay → quote;
  // product_overlay → product_meta. Both fight for the same lower-half
  // search box; the template's elementIds tells us which one to render.
  const lowerKind = allowed.has('product_meta') ? 'product_meta'
                  : allowed.has('quote')        ? 'quote'
                  : null;
  if (lowerKind) {
    // Only product_meta gates on source data — its catalog fields
    // (name + image) are deterministic and present BEFORE derivation.
    // quote text is generated by Gemini AFTER placement, so placing
    // the box always lets the derivation fill it.
    const sourcePresent = lowerKind === 'product_meta'
      ? (!!content?.product?.name || !!content?.product?.image)
      : true;
    if (sourcePresent) {
      const rect = findLeastViolatingRect(analysis, LOWER_BOX);
      elements.push(makeOverlayElement(lowerKind, rect));
      decisions.push({ id: lowerKind, state: 'placed', mode: 'least-violating-lower', rectPct: rect });
    } else {
      skipped.push({ id: lowerKind, reason: 'no product.name or product.image', _missingPath: 'product.name OR product.image' });
    }
  }

  // failedRequired stays empty — without the inset-mode fallback there's
  // nothing to retry. Callers (preview / renderer) that gate on
  // failedRequired.length > 0 will see a clean placement either way.
  return {
    elements,
    skipped,
    failedRequired: [],
    decisions,
    mode: 'overlay'
  };
}

// ── Element shape ────────────────────────────────────────────────────

// Build a placed-element record matching the renderer's expectations.
// rectPct is in canvas fractions; variant + maxLines are downstream
// hints for the per-element render functions in templatePreview.js.
// scrim is left as a no-op chip-bg style is now applied by the
// renderer via style_bindings (testimonial_overlay / product_overlay
// have headline_chip_bg + quote_chip_bg in their normalized template).
function makeOverlayElement(id, rectPct) {
  const base = {
    id,
    rectPct,
    fontScale: 1,
    scrim: { type: 'none', opacity: 0 },
    textColor: '#FFFFFF'
  };
  switch (id) {
    case 'logo':
      base.variant = 'horizontal';
      break;
    case 'headline':
      base.variant = 'horizontal';
      base.maxLines = 2;
      break;
    case 'cta':
      base.variant = 'horizontal';
      break;
    case 'product_meta':
      base.variant = 'product_card';
      base.layout  = 'inline';
      break;
    case 'quote':
      base.variant = 'inline';
      base.maxLines = 4;
      break;
  }
  return base;
}

// ── Least-violating-rect search ──────────────────────────────────────

// Scan candidate rects of size (minW × minH) anchored to a grid of
// SCAN_STEPS×SCAN_STEPS positions inside the search box. Score each by
// overlap with the primary subject (heavily weighted) + density grid
// (lightly weighted). Return the rect with the lowest violation score.
//
// When no analysis is available, return a centered rect of the minimum
// size in the search box.
function findLeastViolatingRect(analysis, opts) {
  const { yMin, yMax, xMin, xMax, minW, minH } = opts;
  const safeYMax = Math.max(yMin, yMax - minH);
  const safeXMax = Math.max(xMin, xMax - minW);

  if (!analysis) {
    const x1 = (xMin + safeXMax) / 2;
    const y1 = (yMin + safeYMax) / 2;
    return { x1, y1, x2: x1 + minW, y2: y1 + minH };
  }

  let best = null;
  let bestScore = Infinity;
  for (let yi = 0; yi <= SCAN_STEPS; yi++) {
    const y1 = yMin + ((safeYMax - yMin) * yi) / SCAN_STEPS;
    const y2 = y1 + minH;
    for (let xi = 0; xi <= SCAN_STEPS; xi++) {
      const x1 = xMin + ((safeXMax - xMin) * xi) / SCAN_STEPS;
      const x2 = x1 + minW;
      const score = scoreRectViolation({ x1, y1, x2, y2 }, analysis);
      if (score < bestScore) {
        bestScore = score;
        best = { x1, y1, x2, y2 };
      }
    }
  }
  return best || { x1: xMin, y1: yMin, x2: xMin + minW, y2: yMin + minH };
}

function scoreRectViolation(rect, analysis) {
  let score = 0;
  const subj = analysis.primarySubjectRectPct;
  if (subj && typeof subj.x1 === 'number') {
    score += rectOverlapArea(rect, subj) * SUBJECT_OVERLAP_WEIGHT;
  }
  const grid = analysis.densityGrid;
  if (grid && Array.isArray(grid.cells) && grid.cols && grid.rows) {
    score += sampleDensity(rect, grid) * DENSITY_WEIGHT;
  }
  return score;
}

function rectOverlapArea(a, b) {
  if (!a || !b) return 0;
  const x1 = Math.max(a.x1, b.x1);
  const y1 = Math.max(a.y1, b.y1);
  const x2 = Math.min(a.x2, b.x2);
  const y2 = Math.min(a.y2, b.y2);
  if (x2 <= x1 || y2 <= y1) return 0;
  return (x2 - x1) * (y2 - y1);
}

// Average density (0..1) of the grid cells the rect intersects, weighted
// by the per-cell intersection area. Higher value = busier region.
function sampleDensity(rect, grid) {
  let weighted = 0;
  let totalArea = 0;
  const cellsAreNested = Array.isArray(grid.cells[0]);
  for (let r = 0; r < grid.rows; r++) {
    for (let c = 0; c < grid.cols; c++) {
      const cell = {
        x1: c / grid.cols,
        y1: r / grid.rows,
        x2: (c + 1) / grid.cols,
        y2: (r + 1) / grid.rows
      };
      const area = rectOverlapArea(rect, cell);
      if (area <= 0) continue;
      const value = cellsAreNested ? grid.cells[r][c] : grid.cells[r * grid.cols + c];
      weighted += (value || 0) * area;
      totalArea += area;
    }
  }
  return totalArea > 0 ? weighted / totalArea : 0;
}

module.exports = { placeOverlays };
